# NumPy

In [1]:
# importing the numpy module
import numpy as np 
print(np.__version__)

1.19.5


In [2]:
# creating the numpy array
x = np.array([1, 2, 3, 4]) 
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
# value at index 0
print(x[0])

1


In [4]:
# create a NumPy array of 3*3
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
 
print(x[1][2]) # print value at row 2 and column 3 ---> 6

6


In [5]:
# defining the array
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 

print(x.ndim) # prints the number of the dimensions in the array ===> 2
print(x.size) # prints number of elements in the array ===> 9
print(x.shape) # prints the shape of the array ===> (3, 3)

2
9
(3, 3)


In [6]:
# defining the array
x = np.array([2, 9, 3])

x = np.append(x, 2) # appends 4 to the array x
x = np.delete(x, 0) # delete the element at index 0 of the array x ----> 2
x = np.sort(x) # sorts the array X -----> [2 3 9]

print(x) # prints the array ----> [2 3 9]

[2 3 9]


In [7]:
# creates an array that contains elements in range(2, 10, 3)
x = np.arange(2, 20, 3)
print(x) # prints the array ---> [ 2  5  8 11 14 17]

[ 2  5  8 11 14 17]


In [8]:
# creates an array of 6 elements ----> in range(1, 6)
x = np.arange(1, 7) # 1-d array ----> [1 2 3 4 5 6]

z = x.reshape(3,2) # change x into a 2-d array -----> [[1 2] [3 4] [5 6]]

In [9]:
# Indexing and Slicing
# creates an array of 9 elements in -----> range(1, 10)
x = np.arange(1, 10) 

print(x[0:2]) # prints ----> [1 2]
print(x[5:]) # prints ----> [6 7 8 9]
print(x[:2]) # prints ----> [1 2]
print(x[-3:]) # prints ----> [7 8 9]

[1 2]
[6 7 8 9]
[1 2]
[7 8 9]


In [11]:
x = np.arange(1, 10) # creates an array of elements 1-9
print(x)
print(x[x%2==0]) # prints the even elements in the array

[1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [13]:
# & ---> and 
# | ---> or 
y = np.arange(31) # creates an array of elements 0-30
print(y)
print(y[(y%3==0)&(y%4==0)]) # prints the elements in the array which are multiple of both 4 and 3
print(y[(y%3==0)|(y%4==0)]) # prints the elements in the array which are multiple of both 4 or 3

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
[ 0 12 24]
[ 0  3  4  6  8  9 12 15 16 18 20 21 24 27 28 30]


## ARRAY OPERATIONS

In [14]:
x = np.arange(1, 10) # creates an array in ----> range(1, 10)
print(x)
print(x.sum()) # prints sum of all the elements of the array
print(x.min()) # prints the minimum element in the array
print(x.max()) # prints the maximum element in the array
print(x*2) # prints the 2*value of each element of the array

[1 2 3 4 5 6 7 8 9]
45
1
9
[ 2  4  6  8 10 12 14 16 18]


In [15]:
print(np.mean(x)) # prints the mean of all the elements in the array
print(np.median(x)) # prints the median of all the elements in the array
print(np.var(x)) # prints the variance of all the elements in the array
print(np.std(x)) # prints the standard deviation of all the elements in the array

5.0
5.0
6.666666666666667
2.581988897471611


### FINAL PROJECT 

In [8]:
import numpy as np

data = np.array([150000, 125000, 320000, 540000, 200000, 120000, 160000,
                230000, 280000, 290000, 300000, 500000, 420000, 100000, 150000, 280000])
m = np.mean(data) # mean of the data
d = np.std(data) # standard deviation of the data
y1 = m-d # mean - standard deviation
y2 = m+d # mean + standard deviation
s = len(data[(data > y1) & (data < y2)]) # within one standard deviation from mean
r = s/len(data)
r*=100
print(r)


62.5
